# Generated by Django 5.1.5 on 2025-03-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_update_field_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='slug',
            field=models.SlugField(default='2025-03-01', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
